name: release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    uses: danielriddell21/github-actions/.github/workflows/release.yaml@v1
    permissions:
      contents: write
      packages: write
    with:
      docker-login: true
      qemu-buildx: true
      homebrew-tap: false
